spring.application.name=M3Project

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd1